"""Replace time_targeted with time_scaled in race_plans (ADR 0005 #637).

The constant-power Mode A optimizer is deleted; target-time plans are
terrain-shaped and produced by the scale-to-time solver. Existing
time_targeted rows are historical (generated by the removed optimizer)
and relabeled time_scaled_legacy to keep the constraint honest while
preserving the record that they came from a different engine.

Revision ID: 030
Revises: 029
Create Date: 2026-08-29

"""

from alembic import op

revision = "030"
down_revision = "029"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Order matters: relax the constraint first, then relabel rows,
    # then install the final constraint.
    op.drop_constraint("valid_optimization_method", "race_plans", type_="check")
    op.execute(
        """
        UPDATE race_plans
        SET optimization_method = 'time_scaled_legacy'
        WHERE optimization_method = 'time_targeted'
        """
    )
    op.create_check_constraint(
        "valid_optimization_method",
        "race_plans",
        "optimization_method IN ('heuristic', 'optimized', 'time_scaled', 'time_scaled_legacy') OR optimization_method IS NULL",
    )


def downgrade() -> None:
    op.drop_constraint("valid_optimization_method", "race_plans", type_="check")
    op.create_check_constraint(
        "valid_optimization_method",
        "race_plans",
        "optimization_method IN ('heuristic', 'optimized', 'time_targeted') OR optimization_method IS NULL",
    )
    op.execute(
        """
        UPDATE race_plans
        SET optimization_method = 'time_targeted'
        WHERE optimization_method = 'time_scaled_legacy'
        """
    )
